name: Build package on different OSs and Python versions

on : [push, pull_request]

jobs:

  build_package:
    name: Build ${{ github.event.repository.name }} on ${{ matrix.os }} for Python-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          - os: macos-latest
            path: ~/Library/Caches/pip
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        name: Install Python-${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}

      - name: Activating Python cache
        uses: actions/cache@v4
        id: cache_python
        continue-on-error: true
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}

      - name: Build ${{ github.event.repository.name }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[doc,tests]"

      - name: Install and run flake8 on Mac
        if: ${{ runner.os == 'macOS' }}
        run: |
          flake8

      - name: Run test on Mac with coverage generated
        if: ${{ runner.os == 'macOS' }}
        run: |
          pytest flagserpy/tests --cov flagserpy --cov-report xml

      - name: Run test on Linux and Windows with no coverage generated
        if: ${{ runner.os != 'macOS' }}
        run: |
          python -m pytest flagserpy/tests --no-cov --no-coverage-upload

      - name: Build sphinx doc on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          cd doc
          python -m pip install -r requirements.txt
          sphinx-build -b html . build

      - name: Upload built documentation and coverage as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ArtifactsCI-${{ matrix.os }}-${{ matrix.python-version }}
          if-no-files-found: ignore
          path: |
            doc/build
            coverage.xml
            htmlcov
