name: Build Wheels

on : workflow_dispatch

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ github.event.repository.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_BUILD: "cp37-* cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-*"
          CIBW_SKIP: "*-win32 *-musllinux_* *_i686"
          CIBW_BEFORE_BUILD_WINDOWS: sed -i $'s/\r$//' README.rst && python -m pip install delvewheel
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair -vv -w {dest_dir} {wheel}"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_ARCHS_MACOS: x86_64 arm64

      - name: Set-up python 3.10 for upload
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install twine
          twine check ./wheelhouse/*.whl
          twine upload --skip-existing ./wheelhouse/*.whl
